### PR TITLE
Test pyerfa on windows as well.

### PR DESCRIPTION
**Pull request by mhvk**
Use the oldest deps so we do some double duty.

### CODE REVIEW

**Comment by mhvk** [comment]
@avalentino - if this passes, it may be an idea to merge quickly and rebase your #53 on it, so that we know we didn't somehow mess up the windows installation.

**Comment by mhvk** [comment]
Oops, I forgot that at the moment everything fails - your #53 is meant to fix it! Shall I push this to your PR?

**Comment by mhvk** [comment]
Actually, silly of me, easier to just rebase on your #53 and check that it works. You can then cherry-pick the relevant commit (or just copy it)

**Comment by mhvk** [comment]
@avalentino - so, on top of your PR, the tests pass, which gives confidence things are OK. I think it is fine now to either include the relevant edits to `.travis.yml` in your PR, or first wrap that up, after which I can rebase this and we get it in too.

**Review by avalentino — APPROVED** [review]
Look good to me.
Feel free to merge as soon as #53 is in.

**Comment by mhvk** [comment]
Well, windows failed now... good that we knew it did work before... Likely same cause as the failures over at astropy: https://github.com/astropy/astropy/pull/10842

**Comment by avalentino** [comment]
Restarted the failing tests but probably this PR should be rebase on top of PR #56

**Comment by mhvk** [comment]
#58 means this is no longer necessary, so closing.

**Pull request closed without merging**
