### PR TITLE
Doc theme debranding

### PR DESCRIPTION
**Pull request by avalentino**

### CODE REVIEW

**Comment by astrofrog** [comment]
Just FYI I've asked the RTD team to enable the RTD pull request preview feature they have, which would make it easier to review PRs like this one!

**Comment by mhvk** [comment]
This looks all OK, but it would indeed be nice to have a way to share how this looks. (Otherwise, I can pull it and try it locally.)

**Comment by avalentino** [comment]
The request to RTD for PR build activation has been done during the week-end, so maybe it is just a matter of waiting a little more.

**Comment by avalentino** [comment]
OK @astrofrog @mhvk , the docs build has been finally triggered.
Thanks to RTD support guys :)

**Pull request merged**
