### PR TITLE
Cleanup makefile and readme

### PR DESCRIPTION
**Pull request by mhvk**

### CODE REVIEW

**Comment by astrofrog** [comment]
Yay for CI! :wink: The submodule should be defined using an https URL not ssh.

**Comment by mhvk** [comment]
@astrofrog - there is a permission error in the travis build: https://travis-ci.org/github/liberfa/pyerfa/builds/683891512

Unfortunately, I don't think I have the required admin permissions to fix this...

**Comment by mhvk** [comment]
OK, sorry, you were just answering me. I'll fix that as part of this PR then!

**Comment by astrofrog** [comment]
(The fix is not just for Travis btw, it is for anyone who doesn't have ssh keys set up)

**Comment by mhvk** [comment]
Yay, first success! I'll go ahead and just merge so we can move forward with #5.

Also realizing we do not yet have a version. But separate issue!

**Pull request merged**
