### PR TITLE
Remove custom build requirements for Python 3.12

### PR DESCRIPTION
**Pull request by pllim**
Just to see what happens.

Blocked by:

* #115

### CODE REVIEW

**Comment by pllim** [comment]
Wait, what? I didn't even touch setuptools_scm stuff, though your version logic is kinda complicated in `setup.py`; is that really necessary?

**Comment by avalentino** [comment]
> Wait, what? I didn't even touch setuptools_scm stuff, though your version logic is kinda complicated in `setup.py`; is that really necessary?

It is to enforce the versioning scheme that always preserves the C ERFA version.
The implementation is indeed quite complicated but at the time I didn't manage to do better.
Any suggestion/patch is very welcome of course.

**Comment by pllim** [comment]
> Any suggestion/patch is very welcome of course.

I am not well-versed in version generation. But the failure is blocking downstream testing over at `astropy` given that you do not publish a dev wheel (#109). I was just going to brute force to remove the logic and let setuptools_scm do its thing.

Either that or you will have to pin `setuptools_scm<8` (https://pypi.org/project/setuptools-scm/#history) which is also not ideal.

**Comment by avalentino** [comment]
> Either that or you will have to pin `setuptools_scm<8` (https://pypi.org/project/setuptools-scm/#history) which is also not ideal.

Probably at the moment it is the fastest solution, at least for the short term.
I will try to look into the issue during the week-end but I cannot guarantee, this is a very busy period for me.

**Comment by pllim** [comment]
This is ready for review. Thanks!

**Review by avalentino — APPROVED** [review]

**Comment by avalentino** [comment]
Thanks @pllim , amazing job! :)

**Pull request merged**
