### PR TITLE
Do not package generated files

### PR DESCRIPTION
**Pull request by avalentino**

### CODE REVIEW

**Review by mhvk — APPROVED** [review]
How weird, I did not see a message about this. I think this would definitely help avoid version problems, thanks!!

**Comment by mhvk** [comment]
Upon merging the tests failed because I think some interaction with the tag that I had pushed. But with the new tag all is OK. Thanks again!!

**Comment by avalentino** [comment]
Thanks @mhvk.

Actually I have just realized that ``m4/erfa-numver.m4`` is in scm so probably it is better to leave it in also if it is not strictly necessary.
Will do another PR for that.

**Comment by avalentino** [comment]
Done, see PR #67

**Pull request merged**
